// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "profiles": string;
      "activeProfileId": string;
      "mode": string;
      "langIn": string;
      "langOut": string;
      "output": string;
      "pages": string;
      "qps": number;
      "poolMaxWorkers": number;
      "noAutoExtractGlossary": boolean;
      "ocrWorkaround": string;
      "customSystemPrompt": string;
      "glossaryFile": string;
      "watermark": boolean;
      "bilingualLayout": string;
      "enginePath": string;
      "downloadURLPrefix": string;
      "autoOpen": boolean;
    };
  }
}
